### ISSUE TITLE
[VisuWorkspace] removing first tab block the view/layer toolboxes

### ISSUE THREAD

**Issue by mathildemerle** [medInria/medInria-public#1066]
In medInria 3.3/3.4/4.0: 
 * open 2 tabs with data, 
 * close the first tab, 
 * the first one is not "linked" anymore to the view/layer/toolboxes and can't be used anymore **-> bug**
 * to reset the view, CTRL-click twice

**Comment by paulineMig** [comment]
Since we are talking about tabs problems in visualization:

- open 2 tabs with data,
- inverse th position of the 2 tabs
-  the view/layer/toolboxes are not link to the right data anymore

**Comment by mathildemerle** [comment]
Indeed, i was working on it on : https://github.com/medInria/medInria-public/issues/517 when i found this one. I'm going to post a PR with a debug for the tab problems today
