### ISSUE TITLE
Cannot select multiple files loaded in medInria

### ISSUE THREAD

**Issue by bishesh** [medInria/medInria-public#198]
I cannot select multiple files that are present on the left window pane under (Patient/Study/Serie). 
I usually have to visualize many files at the same time so I select all of them from the hard disk using "Browser" and then use the action "Load". 
After working with them when I want to "remove" these files, I have to remove the files individually since I can't select all of them together. I want to remove them to free up the RAM space and load other images for visualization.

**Comment by mathildemerle** [comment]
This is solved
