### ISSUE TITLE
In the settings menu, buttons have non friendly behavior

### ISSUE THREAD

**Issue by rdebroiz** [medInria/medInria-public#216]
IMO, in the settings menu, the reset button have the effect that the cancel button should have. The cancel button seems to do nothing

**Comment by mikejbuckingham** [comment]
I'm assuming reset should revert us back to the 'default' settings (and perhaps the button should be renamed default?), and cancel should undo any changes that haven't been saved?

**Comment by rdebroiz** [comment]
I agree with you.

**Comment by mathildemerle** [comment]
This could be changed during the improvement of homepage in 4.1: https://github.com/medInria/medInria-public/issues/446

**Comment by mathildemerle** [comment]
Solved by https://github.com/medInria/medInria-public/pull/870
