### ISSUE TITLE
Thumbnail access

### ISSUE THREAD

**Issue by rdebroiz** [medInria/medInria-public#225]
For now there are two ways to access the thumbnail of a data:

``` c++
QImage& medAbstractData::thumbnail() 
//it should return QImage or QImage const&  IMO by the way

QPixmap medDataManager::thumbnail(const medDataIndex& index); 
// the method should be const IMO by the way
```

The problem is that the first one is not an accessor, it actually tries to generate a thumbnail if the `d->thumbnail` attribute is an empty image. Since there is no setter to this attribute it's always the case...

IMO we should fuse this method with `void medAbstractData::generateThumbnail()` 
which is private and make it friends with the class that are actually supposed to do that, which are `medDatabaseNonPersistentImporter` and `medAbstractDatabaseImporter` apparently. So the medDataManager will be the only access point to the thumbnails.

**Comment by mikejbuckingham** [comment]
I agree in principal with the idea of merging the methods, but I'm not sure I see the reason for friendship - why not simply publicise the generateThumbnail method?

Agree on the const-correctness, and probably renaming stuff to be more explicit (getThumbnail vs thumbnail)

**Comment by rdebroiz** [comment]
> - why not simply publicise the generateThumbnail method?

Because it can crashes if it is improperly called. For example it crash if you call it from a non smart pointed data (but maybe the real probleme is that we can manipulate data that have not be smart pointed at least once ;-)). Plus I can't find other cases than import  where it can be usefull.

**Comment by fvichot** [comment]
Actually, apart from the const-correctness which I agree should be just QImage, and probably even QPixmap for consistency with the other method, the rest I don't agree. ```medAbstractData::thumbnail()``` and ```medDataManager::thumbnail()``` have different roles. The first one is to get the thumbnail from a loaded data object, the second is for loaded a thumbnail from a DB item, without loading it.

**Comment by fvichot** [comment]
Grrr I was going to change the signature from ```QImage&``` to ```QPixmap``` in PR #224 , but obviously since it's a method from dtkAbstractData, I can't change the return type without also changing the name. So do I leave it like that with a comment to change it when we get rid of the dtkAbstract* stuffs, or should I change it to ```getThumbnail()``` or something and do it now?

**Comment by rdebroiz** [comment]
Ok, since only images aka series can have thumbnails, and because thumbnails have sense only in the database i can't see why ```medAbstractData::thumbnail()``` should exists.

We could just move the equivalent of the ```medAbstractData::generateThumbnail()``` into the importers but I fear to encounter some troubles due to the fact that this work have to be done in the graphic thread.

IMO we should just have a ```private  medAbstractData::generateThumbnail()``` to create the thumbnail,  a  ```medAbstractData::generateThumbnailFromGuiThread()``` to check the thread stuff and call the previous method, and a ```medDataManager::thumbnail(medDataIndex index)``` as an access point to the thumbnail of the corresponding dataIndex. when the importers need to create the thumbnail associate to a data they call ```medAbstractData::generateThumbnailFromGuiThread()``` on the data.

**Comment by fvichot** [comment]
Well, for now everything can be opened in a medVtkView because it's the only type of view we have, but if tomorrow we add a medPlotView or whatever, then having the code to render a thumbnail being in the importer means that we can't change the implementation of how to render a thumbnail based on the data type without having some horrible ```switch/case``` on the data type in the importer's code. Having it in medAbstractData just makes a lot more sense, where it can be re-implemented in a derived class if necessary. So we can't move this code in the importers. Then you suggest that we have a ```generateThumbnail()``` and a ```generateThumbnailFromGuiThread()```. Honestly, apart from slightly clearer naming, this doesn't really change anything to what we have ?

At best, I can be convinced to replace ```thumbnail``` with ```generateThumbnail()``` in medAbstractData, to make it clearer that this will will generate a new thumbnail every time, and getting rid of the thumbnail attribute, but not make it private, I really don't see the issue with it being public. It's fairly likely that at some point we'll need to generate thumbnails for data not in the database, to have preview of a filter step for example. We should probably make the signature be ```QPixmap generateThumbnail(QSize size)``` for flexibility.

I'm happy to make that change in PR #224 if you're OK with it.

**Comment by rdebroiz** [comment]
> Well, for now everything can be opened in a medVtkView because it's the only type of view we have, > but if tomorrow we add a medPlotView or whatever, then having the code to render a thumbnail be 
> in the importer means that we can't change the implementation of how to render a thumbnail based > on the data type without having some horrible switch/case on the data type in the importer's code. 
> Having it in medAbstractData just makes a lot more sense, where it can be re-implemented in a 
> derived class if necessary. So we can't move this code in the importers.

I was thinking about it after I wrote my comment and i agree with you finally.

> I can be convinced to replace thumbnail with generateThumbnail() in medAbstractData, to make it 
> clearer that this will will generate a new thumbnail every time, and getting rid of the thumbnail  
> attribute,

that's what I intended to do. And i really think it has to be done, to prevent someone to call this method to get a thumbnail from a data while it actually regenerates one each times.

> but not make it private, I really don't see the issue with it being public. It's fairly likely that at some  
> point we'll need to generate thumbnails for data not in the database, to have preview of a filter step > for example. 

My problem with that was that if it's called while the data has not be smart pointed, it deletes the data, so it can be dangerous to call this method. But i guess the problem comes more from the way we manipulate our data and smart pointed data.

> We should probably make the signature be QPixmap generateThumbnail(QSize size) for flexibility.

Nope, not IMO, QPixmap is fast to display an image on the screen, QImage, is fast to read / write / manipulate buffer of an image, since this method will be called most of the time to create and save a thumbnail in the database it sounds legit to me to create and return a QImage (and it sounds legit to me that the access point of this thumbnail from the database return a QPixmap since most of the times it will be called to display it) .

> I'm happy to make that change in PR #224 if you're OK with it.

Cool, I'm OK, if you have time you can also clean the way thumbnails are stocked and retrieve from the database, i feel like if we're still manipulating list of images / path for one serie, at some point which has no sense any more since we now always have only one thumbnail for one serie.

**Comment by rdebroiz** [comment]
I forgot: 

About the name of the method in medAbstractData, finally I think that `private QImage medAbstractData::generateThumbnailFromView()` and `public QImage medAbstractData::generateThumbnail()` would be more relevant if someone want to overrides the way to genarate a thumbnail it have not necessarily to be done from the GUI thread. Plus, it's more intuitive to call  `generateThumbnail` than `generateThumbnailFromGuiThread`. 
and `generateThumbnailFromView()` is a better description of what it actually does.

Sorry about changing my point of view again and again...

**Comment by fvichot** [comment]
OK, let's merge #224 for now if you're good with it, and I'll do these changes in another PR, as I'm also cleaning the DB it's getting off topic.
