### ISSUE TITLE
Screenshot button doesn't work

### ISSUE THREAD

**Issue by mikejbuckingham** [medInria/medInria-public#236]
When screenshotting an image in visualisation, I get a black screen with the borders from the view.

**Comment by rdebroiz** [comment]
What is your configuration ? This is probably related to your GPU / driver / OpenGL implementation.
(It works for me)

**Comment by mikejbuckingham** [comment]
Intel GPU, linux. I've seen it on another machine, that has the same configuration. I guess it's another mesa bug! Thanks :)
