### ISSUE TITLE
Preset changes LUT, LUT does not change preset

### ISSUE THREAD

**Issue by NicolasSchnitzler** [medInria/medInria-public#240]
When selecting a preset item in the combobox, the LUT is changed accordingly (i.e. if one selects "Vascular II", LUT is automatically set to "Red Vessels".

When changing the LUT though, preset does not change.

This implies that, when reloading a scene, preset has to been reloaded before LUT.

Is it by design (same behaviour on all workspaces)?

**Comment by Hakim-F** [comment]
I think a preset, is a specific LUT with a certain Window/Level value, not sure, but It is by design.
