### ISSUE TITLE
Save Mask button in PaintSegmentationTbx

### ISSUE THREAD

**Issue by LoicCadour** [medInria/medInria-public#242]
I wanted to make a test on this toolbox on the last version of medInria, and I noticed that the "Save" button has disappeared. I think this is a problem, because now we cannot create to masks from a volume.
Once you start painting a mask, it automatically creates a non-persistent data. You can of course make that mask persistent through the db feature, but after that you're stuck; for creating a new mask on this particular volume, you have to restart medInria.
I might be missing something but it might be good to have this "Save" button back. Does anyone know why it has been removed?

**Comment by ocommowi** [comment]
It's probably linked to the introduction of the undo/redo, plus data handling change. I like it as it is but if you think it's missing we could think of having it back. What would you think of a "Save copy" or duplicate button that would not change the stack of actions but rather create a new copy of the mask in the non persistent database ?

**Comment by LoicCadour** [comment]
Yes, I like this solution; it can even save the copy in the persistent database.
What I was trying to test actually was the possibility of saving several independent segmentations on a single volume, playing with the "Save" and "Clear" buttons that we still have in MUSIC.

**Comment by Florent2305** [comment]
Paint plugin will be probably redo by MUSIC team AND/OR by futur engineer work for APHP at Sophia.

**Comment by mathildemerle** [comment]
This issue has been solved. Paint Segmentation toolbox has been updated to a new version, and there is a "Save" button :)
