### ISSUE TITLE
Importing or loading data with duplicate info can lead to very slow loadtimes

### ISSUE THREAD

**Issue by mikejbuckingham** [medInria/medInria-public#248]
This log (or similar) pops up for some data:

W: DcmItem: Element (0000,0000) found twice in one dataset/item, ignoring second entry

This massively increases the amount of time taken to load/import the data, as it is printed many thousands of times.

Three ways to handle it:

1) Keep track of duplicate logs and don't print them
2) Remove this log
3) Have different logging levels, so this one only appears when we're debugging.

**Comment by Florent2305** [comment]
Maybe solved by Mathilde's PR

**Comment by mathildemerle** [comment]
The problem is that i can't test for now, we don't have dicom with duplicated data ^^'
