### ISSUE TITLE
Objectives 3.0

### ISSUE THREAD

**Issue by rdebroiz** [medInria/medInria-public#261]
This lists more or less global objectives. Bugs can be listed here if small, if they need discussions, please add them as separate issues with the milestone 3.0
- Various things
  - [ ] Close all issues with milestone 3.0 (or remove their milestone)
- Process refactoring
  Design the new medProcessLayer (ie, new abstractions) and port all the existing plugins to the new plugins system
  - [x] filtering processes
    - [x] arithmetical operations | merged https://github.com/medInria/medInria-public/pull/263
    - [x] morphological operations | merged https://github.com/medInria/medInria-public/pull/267
    - [x] gaussian blur
    - [x] update filtering workspace to use new processes.
  - [ ] segmentation processes
  - [x] diffusion processes
  - [ ] Parameters have not all been translated to the new split (parameter plus its presenter): would be cool to have, especially for a diffusion plugin where I would need the medBoolGroupParameter and its presenter
  - [ ] Adapt all concerned workspaces to use the new processes and discard legacy ones for workspaces where we can
- CMake 3
  - [x] get rid of the warnings | merged https://github.com/medInria/medInria-public/pull/265
  - [x] improve management of  output directories, using target properties instead of global variables | merged https://github.com/medInria/medInria-public/pull/265
  - [x] simplify dll symbol exports management, using the target property DEFINE_SYMBOL | merged https://github.com/medInria/medInria-public/pull/268
- Jenkins
  - [ ] update jenkins (rebuild from the ground up I guess) to fit the new medinria repos (no more superproject, plugins in two folders or not...)
- VTK 7 support
  - [x] Switch superproject to VTK 7
  - [x] Make everything compile with the new VTK
  - [ ] Display annotations correctly on views (looks fine on Mac with VTK7, check on other platforms)
  - [ ] Ensure visualization is as fast as in the previous release (window/leveling, with multiple views linked...)
  - [ ] Make sure tensors and other glyphs are correctly displayed in all situations, without an awful lot of console warnings
- Composer partial support
  - [ ] Use our own widget, with only the toolboxes / sub-widgets we need
  - [ ] Implement nodes for all our abstractions (only the non legacy processes, which means no registration)
  - [ ] For a node, be able to select the process falling in that category, and have a toolbox (coming from the presenter) with its parameters shown somewhere in our area
  - [ ] Save compositions (may be not process selection and process specific parameters but at least the nodes and how they are plugged)
  - [ ] Update stylesheet
- Qt5
  - [ ] Switch private projects to Qt5 and new superproject (partially started with the diffusion branches)
- Application (may be)
  - [ ] Make use of the dtkApplication class, (simplify log, local and cmd line arg management)
- Log (may be)
  - [ ] Use the dtk log system everywhere and properly 
- Clean up 
  - [ ] Get rid of all the unused medFooLegacy things.
  - [ ] Clean up the dev branch, use correct names for classes, avoid redundant code if we can

**Comment by Florent2305** [comment]
See #290 and #335
