### ISSUE TITLE
Facilitate image import

### ISSUE THREAD

**Issue by msermesant** [medInria/medInria-public#282]
Talking with clinicians, they have a hard time opening an image when launching medInria for the first time. This should not be the case. But it is not intuitive to have to go to "database", then see that there is a tab called "filesystem", and guess that it is where the import is done.
I would suggest that we add a big "Open Image" button on the home page that goes directly the file system, and switches to the database when the import is done.
I would also put this button in the database tab, to switch to the filesystem one.

**Comment by Florent2305** [comment]
I think, if this "enhancement" is applied , I suggest to switch to view.
