### ISSUE TITLE
Long term objectives

### ISSUE THREAD

**Issue by ocommowi** [medInria/medInria-public#290]
This groups subjects that we will not address for the next release (3.0). But these topics are definitely of interest so let's not forget about it.
- Gui port 
  port the existing gui things to the new medGuiLayer, maybe merge the medAbstractArea and the medAbstractWorkspace.
  - [ ]  medToolBox -> not sure if having dynamic toolbox is really needful.
  - [ ]  medSettingsWidget -> not sure it is really needful as well.
- Data refactoring
  Don't use template for all image data and make the type esolution relying on enum rather than string. see https://github.com/medInria/medInria-public/issues/233. Port all the existing data plugins to the new dtk plugin system.
  - [ ] image data refactoring
  - [ ] itk image plugin port 
  - [ ] vtk fiber plugin port
  - [ ] vtk mesh plugin port
  - [ ] gradient list plugin port 
- Process refactoring
  - [ ] registration process
- View port
  - [ ] port the view plugin to the new dtk plugin system (note that during an hackfest the dtk guy suggest us to directly incorporate the medVtkView to the lib shared by medInria)

**Comment by Florent2305** [comment]
It's too old for me and not very in correlation to medInria 4.x
