### ISSUE TITLE
Image arithmetic filtering in v3.0

### ISSUE THREAD

**Issue by gpasquie** [medInria/medInria-public#320]
Hello all and congrats for the new version.
It's nice to see that's it's finally going to be released!

I tried it quickly this morning and it seems that there are some issues with the image arithmetic filters...I tried to add or subtract images and nothing happens...other filters seem to work fine.

GP

**Comment by ocommowi** [comment]
Hi ! Thanks for testing. I tried this morning to subtract two images and it seemed to work fine. Do you have example images to illustrate the bug ?

**Comment by gpasquie** [comment]
My bad. Actually it works, but there is just one case where I cannot manage to subtract or add images...I tried to segment one image and then to add or subtract my segmentation to my image and there, nothing happens, and there is no log as well...but maybe it's because there are not of the same type?
