### ISSUE TITLE
Segfault when switching to "4 views" with vector image

### ISSUE THREAD

**Issue by truenicoco** [medInria/medInria-public#322]
# Configuration

Using nightly `medInria-3.0-Fedora_25-x86_64.zip` build from `07-Feb-2018 00:21` under Fedora 27.

# Steps to reproduce

1. Open visualization workspace
2. Load vector image
3. Click the *4* icon

# Attachments

- [logs (stderr and stdout)](https://github.com/medInria/medInria-public/files/1703174/medinria-segfault.txt)
- [Example MHA image provoking the issue](http://www-sop.inria.fr/members/Nicolas.Cedilnik/files/10by10by10tensorimage.mha)

**Comment by Florent2305** [comment]
Solved by #324
