### ISSUE TITLE
Freeze when trying to load "realistic" vector image

### ISSUE THREAD

**Issue by truenicoco** [medInria/medInria-public#323]
# Configuration

Using nightly `medInria-3.0-Fedora_25-x86_64.zip` build from `07-Feb-2018 00:21`.
Running Fedora 27.

# Description

MedInria freezes when trying to load a `255x384x480x3` vector image. The behaviour looks kind of random, as another attempt ending up in filling my 16 GB of RAM, with `vtkVOIsomething` errors in `stderr` that I unfortunately didn't record. This time it was a bit better, as it did not completely lock my PC until I was able to kill the process.

# Steps to reproduce

1. Open visualization workspace
2. Load vector image
3. (optional) Helplessly try to click anywhere or do anything
4. (optional) `CTRL+C` in terminal to soothe the pain

# Attachments

- [stderr and stdout](https://github.com/medInria/medInria-public/files/1703229/medinria-freeze.txt)
- [Example MHA image provoking the issue](http://www-sop.inria.fr/members/Nicolas.Cedilnik/files/big_tensor_image.mha)

**Comment by msermesant** [comment]
Visualisation of vector images should start with a sampling of 4, because the default of 1 is generating a lot of useless glyphs, which are filling up all the memory...

**Comment by Florent2305** [comment]
We change the sampling from 1 to 2. This modification generates less glyphs and the memory consumption rises a maximum of 3.4GB on my PC.
This correction is into the pull request #324
Normally it will be available into the master tomorrow.
I'm sorry It is not possible to do more for the moment on this problem. If It's not enough for you I will  try to increase the sampling up to 4.

**Comment by ocommowi** [comment]
Well it works for me as well like this. I'm closing the bug, don't hesitate to open it again if needed
