### ISSUE TITLE
fullscreen mode in 3.0

### ISSUE THREAD

**Issue by alegouhy** [medInria/medInria-public#325]
Can not modify lut, preset or access to tools in fullscreen mode.
When clicking, nothing happens.

on Windows 10.0.15063

**Comment by ocommowi** [comment]
May be related to this https://bugreports.qt.io/browse/QTBUG-41309

Several workarounds are proposed, we could try them

**Comment by Florent2305** [comment]
Workaround on pull-request #326

**Comment by ocommowi** [comment]
Normalement c'est regle. Je ferme, tu pourras rouvrir si ca marche pas
