### ISSUE TITLE
https://github.com/d-tk/dtk.git doesn't exist anymore?

### ISSUE THREAD

**Issue by nisaea** [medInria/medInria-public#337]
`superbuild/projects_modules/dtkImaging.cmake` and `superbuild/projects_modules/dtk.cmake` define as a git url for DTK an address that apparently doesn't correspond to any existing GitHub repo.

Is https://github.com/d-tk/dtk.git temporarily closed? Has it moved?

I've tried to use an Inria hosted DTK repository a collegue of mine uses and is known to work for her (git://dtk.inria.fr/+medinria/dtk/dtk-clone-medinria.git), but include(s?) fail as shown below:
```
In file included from /home/louisa/Git/medInria-public/src/layers/legacy/medCoreLegacy/parameters/medAbstractParameterGroupL.cpp:19:0:
/home/louisa/Git/medInria-public/src/layers/legacy/medCoreLegacy/views/medAbstractView.h:16:44: fatal error: dtkCoreSupport/dtkAbstractView.h: Aucun fichier ou dossier de ce type
 #include <dtkCoreSupport/dtkAbstractView.h>
```

Is there a way to work around this?

Thanks

**Comment by ocommowi** [comment]
We have realized this just a week or so ago. Dtk has been transfered to another git host. We are working on changing this as soon as possible

**Comment by papadop** [comment]
Educated guess.... It has been moved to gitlab.inria.fr... But yes they should have warned people...

**Comment by nniclausse** [comment]
yes, dtk is now available here: https://gitlab.inria.fr/dtk

**Comment by nisaea** [comment]
Hum this is awkward :D 

Indeed, I modified l.43 of both files with `git@gitlab.inria.fr:dtk/dtk.git` instead of `${GITHUB_PREFIX}d-tk/dtk-imaging.git` and it seems to compile just fine.

Thanks for the help!

Which branch should I be looking at for the upcoming changes on this issue?

**Comment by ocommowi** [comment]
It is still a bit ugly cause we are working on it (the branch is not clean yet) and another thing came out in the process but the pull request is there #336

**Comment by nisaea** [comment]
Awesome! master it is then, tho I've encountered missing find_package() calls in that branch, should I open an issue for that or are you working on it as well already?

**Comment by ocommowi** [comment]
The official correcting branch has been merged to master. You can update, tell me if it doesn't work

**Comment by nisaea** [comment]
so far so good, thanks! :]

guess I can close since the fix made its way to master
