### ISSUE TITLE
Can't load DICOM data

### ISSUE THREAD

**Issue by nisaea** [medInria/medInria-public#339]
Hello,

I'm trying to load DICOM MRI data in medInria but for every file I get this error:

```
E: can't load data dictionary
DEBUG - mer. août 1 11:39:02 2018 - Unrecognized component type:  0 
WARN  - mer. août 1 11:39:02 2018 - Reader was unable to read:  "/path/to/file" 
```
This issue was observed on both Mac and linux, on the 3.0.0 version

**Comment by mathildemerle** [comment]
Solved by https://github.com/medInria/medInria-public/pull/352

**Comment by mathildemerle** [comment]
This issue can be closed (i don't have the rights to close it)

**Comment by Florent2305** [comment]
It's Ok, I close it.
