### ISSUE TITLE
AE title field limited to 6 characters

### ISSUE THREAD

**Issue by isolovey-robarts** [medInria/medInria-public#340]
AE Title field in Dicom servers settings is limited to 6 characters

Running v3.0.0 on macOS 10.13.6

**Comment by ocommowi** [comment]
The same goes here, I sent the bug to the other repo

**Comment by Florent2305** [comment]
Bug is into QtDcm

**Comment by ocommowi** [comment]
Well this actually works in current medinria development builds. You need to input your aetitle in capital letters but no limitation
