### ISSUE TITLE
désynchronisation des vues

### ISSUE THREAD

**Issue by alegouhy** [medInria/medInria-public#347]
yo,
quand on a 2 vues ou +, si:
   1. on ouvre une image dans chacune des vues
   2. on retire le layer de l'une des vues 
   3. on reouvre une image dans cette même vue
alors, il n'est plus possible de synchroniser les 2 vues.

edit: la désynchro n'est qu'en terme de zoom. Le scroll des slices, translations et contrast sont ok.
edit2: ça remarche lorsque l'on change d'orientation

**Comment by Florent2305** [comment]
Ok je prends en charge
