### ISSUE TITLE
[Build] external libraries building

### ISSUE THREAD

**Issue by mathildemerle** [medInria/medInria-public#376]
Some comments:

 * When i compile `medInria`, i clone it, enter it, create a "build" directory, enter it, apply "cmake ..", and then "make" -> usually, everything should be built here in this `build`directory. But, only the `medInria-build` part has been compiled here, and after a search, the thirdparts have been compiled outside the `build` directory, and outside the clone. I am not sure this is a good behavior. I think it would be better to compile everything natively where you build, in two directories if you want: medInria and thirdparts. It would be less confusing.

 * Because of a compilation error, i changed something in an external projects `TTK.cmake`, remove the directories TTK of src and build in the ExternalProjects directory (outside the clone). Then i went back to `build` and applied "cmake" and "make". I had a compilation error. It would be fine to allow to remove and recompile a thirdpart if we want.

**Comment by Florent2305** [comment]
Bonjour Mathilde,

Sur le premier point c'est bien le comportement attendu.
Pour obtenir le comportement que tu souhaites il faut utiliser EP_CHECKBOX_ON_TOP_LEVEL dans le cmake du super projet.
Pour encore plus finement régler ce genre de path, il est aussi possible de jouer avec :
- EP_PREFIX     
- EP_PATH_SOURCE
- EP_PATH_BUILD 

Au besoin je peux faire une petite formation sur ce point pour ceux qui le souhaite.


Pour le second point je comprend bien le problème mais je ne l'ai pas encore rencontrer personnellement. Je laisse donc cette issus ouverte pour ce point.

**Comment by mathildemerle** [comment]
Une petite formation, ou une doc pourrait aider oui :). 

Mais sinon, on ne devrait pas checker le bouton "EP_CHECKBOX_ON_TOP_LEVEL" de base ? Et si les utilisateurs ou utilisatrices veulent installer les lib ailleurs, elles peuvent le dé-checker.

**Comment by Florent2305** [comment]
Je te propose d'en discuter cet après-midi au téléphone, là je suis en réunion.
Je suis partant pour faire une petite formation en plus d'une doc. Après la question que je me pose c'est qu'il serait peut-être utile de faire une doc complète du cmake du super-projet et du cmake du projet.

**Comment by mathildemerle** [comment]
Oui, pas de soucis, c'est pas urgent :)

**Comment by mathildemerle** [comment]
Small problem linked:

 * In the medInria-public clone, create a `build ` directory, enter it
 * Put `EP_CHECKBOX_ON_TOP_LEVEL` to off, then `cmake ..` and `make`
 * An ExtProjs directory is created in build with the built external libraries -> OK
 * An ExtProjts directory is created in ".." in the clone with libraries sources -> OK
 * On top level, on same path as the clone, there is a `medInria-public_ExtProjs` directory including build and src directories, with each external libraries directory, but empty -> NOK

**Comment by Florent2305** [comment]
Oui en effet, c'est connu et c'est pas vraiment un problème mais plus un effet de bord de CMake.
Je m'explique.
CMake lors de sa première execution va générer le repertoire des EP.
Donc dans ton cas avec  EP_CHECKBOX_ON_TOP_LEVEL  à ON.
Puis au changement il ne fait pas le ménage.
De plus dans certain cas tu peux vouloir jouer avec deux repertoires ExtProj différents pour tester différente config et la tu ne souhaites plus qu'il efface le dossier.

Pour contourner cela c'est très simple:
cmake <build dir> -DEP_CHECKBOX_ON_TOP_LEVEL OFF

ou alors faire une PR enhancement où
avant de créer le nouveau répertoire on prend l'ancienne valeur de la variable
on vérifie que le repertoire existe et est vide et là on le supprime.
