### ISSUE TITLE
Bad view resize

### ISSUE THREAD

**Issue by Florent2305** [medInria/medInria-public#414]
Into tab with multiple views, when you close some view you can have a bad behavior of resizing for keeped views.

Issues from #335

**Comment by mathildemerle** [comment]
I do not succeed to recreate this bug. Does it still here? Do you have to open multiple views during a really big time? Does it include maximize views, or 4-split views?

**Comment by Florent2305** [comment]
I postpone this bug correction to 4.1

**Comment by mathildemerle** [comment]
Should be linked to https://github.com/medInria/medInria-public/pull/1067
