### ISSUE TITLE
[website] medInria website certificate problem

### ISSUE THREAD

**Issue by mathildemerle** [medInria/medInria-public#454]
On the medInria website http://med.inria.fr/ you can have a security certificate problem. The connection is displayed as non-secured.

**Comment by ocommowi** [comment]
In fact the certificate is too old and I am not able to update it. I have emailed people in Sophia to update the certificate. Once it is done, I'll update the website to be fully https

**Comment by ocommowi** [comment]
Done, thecertificate is back on track and the full site is SSL now
