### ISSUE TITLE
[Generic Workspace] use as medSelectorWorkspaces

### ISSUE THREAD

**Issue by mathildemerle** [medInria/medInria-public#460]
A discussion about the current and/or future workspaces.

"Legacy" selector workspaces can be generated and registered in plugins (plugins here, or in external projects). For instance, Filtering, Meshing, Reformat, Registration and Segmentation are plugins on this repository.

The Generic Workspace (which is "non-Legacy", or "dtk2") buttons in the Settings buttons on homepage under medInria description could perhaps in the future be removed to let users create their own workspaces as they want.

**Comment by Florent2305** [comment]
The generic Workspace  like it is actually will be remove on 4.1

But keep the concept of generic Workspace can be a good way. This to create a plugin without re-generate a complet Workspace but just custom a "new generic Workspace".

Unless the gain is too small ...
