### ISSUE TITLE
missing method in medAbstractView!! 

### ISSUE THREAD

**Issue by nebatmusic** [medInria/medInria-public#480]
This method has removed from medAbstractView (medCoreLegacy) 
virtual QMainWindow* mainWindow(). 

It is used by some of our external plugins. 

Is there a technical reason for that ?

Thanks.

**Comment by mathildemerle** [comment]
Oki, where is it used? In order to test :)

**Comment by mathildemerle** [comment]
There is a new way to find this QMainWindow.

Before for instance in itkFilters:
`medVtkView->mainWindow()->parentWidget()->layout()->addWidget(d->clutEditor);`

Now:
`medVtkView->viewWidget()->layout()->addWidget(d->clutEditor);`

**Comment by nebatmusic** [comment]
It is in music-plugins-liryc/Carmen/plugins/mscMeshInteractor/mscMeshInteractor4D.cpp. 

But it seems strange because  previous implementation seems to return nullptr. 

So i think I will adopt your solution but in a first step I will set it to null. 

Thanks.

**Comment by mathildemerle** [comment]
I updated the documentation on music to explain it. I'll close this issue since it's solved.
