### ISSUE TITLE
Windows package very large

### ISSUE THREAD

**Issue by ocommowi** [medInria/medInria-public#481]
It seems that the windows medinria package has grown a lot since medinria 3.0. There might be a packaging problem that appeared due to our changes. To be checked

**Comment by Florent2305** [comment]
It's a well known problem of packaging and/or generation files emplacement ( .pdb .ilk .exp etc)
Two solutions can be combine:

- Change place of  .pdb .ilk .exp etc generation
- package only .dll and .exe
