### ISSUE TITLE
[medInria 3.0] binary crash xcb Qt5

### ISSUE THREAD

**Issue by mathildemerle** [medInria/medInria-public#487]
A colleague tried the medInria 3.0 binary for Ubuntu 16 on a Ubuntu 18. He switched his OS to Qt5 with `sudo apt install qt5-default`, run the medInria script and crash:

```
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
Abandon (core dumped)
```
It's maybe solved on the master, or it's a pre-requisites problem, i don't have the crash.

**Comment by ocommowi** [comment]
It sounds like you are missing Qt5 dependencies on the system. Something we need to document by the way. On the slaves for build, I think we have explicitly installed :

- for ubuntu : qt5-default qttools5 qtdeclarative5 libqt5x11extras5 libqt5svg5
- for fedora : qt5

That's one point in favor to go back to a rpm or deb packaging, this could solve those problems

**Comment by mathildemerle** [comment]
Pre-requisites for running medInria added in https://github.com/medInria/medInria-public/wiki/A-Quick-Dev-Guide
