### ISSUE TITLE
Window/level lag with several layers

### ISSUE THREAD

**Issue by ocommowi** [medInria/medInria-public#492]
Another visualization bug that probably dates back from medinria 3.0. Do the following : 

- load and view CT_mouse.mha from medinria-data
- check that window/leveling does not lag yet (e.g. with the mouse or controls on the right)
- now load as a second layer SPECT_mouse.mha still from medinria-data
- click on the CT layer on the right panel
- now the window/leveling is extremely slow and lagging

**Comment by mathildemerle** [comment]
Weirdly, there is no lag if you begin to open SPECT and then CT.

**Comment by msermesant** [comment]
probably normal, as I think the rendering resamples the (high) resolution of the CT on the (low) resolution of SPECT when you drop it on top.

**Comment by ocommowi** [comment]
It's better on my mac but the lag problem is still not solved

**Comment by mathildemerle** [comment]
Ok, i changed the description of #518. The PR helps because it solves 1 problem, but an other problem remains.

**Comment by Florent2305** [comment]
move to 3.1.1
