### ISSUE TITLE
[Documentation] quick dev guide

### ISSUE THREAD

**Issue by mathildemerle** [medInria/medInria-public#498]
I made a guide for dev: [Quick-Dev-Guide](https://github.com/Florent2305/medInria-public/wiki/Quick-Dev-Guide) which is based mostly on MUSIC documentation. I've seen with @Florent2305 to add it on his wiki.

A small guide is really used on our side, we can find the information to install pre-requisites, compile and run the application quickly. On Linux and Mac, we prefer to install everything with (really few) command lines. I think this is needed for the 3.1 release, because new devs are coming on medInria 3 from Bordeaux.

Some info are missing on my guide: 
  
- [x] the Fedora minimum version
- [x] the Mac minimum version
- [x] the Fedora pre-requisites (we do not have Fedoras on our side)
- [x] the pre-requisites to run medInria binary (not compilation)
- [x] the Windows compilation by terminal (for our continuous integration)

Later, maybe for 4.0: a paragraph to explain how to use medInria with external plugins (for now, it could be how we do it on our side?)

If you have these informations, i can add it to the doc, do not hesitate.

**Comment by msermesant** [comment]
👍

**Comment by mathildemerle** [comment]
NB https://github.com/medInria/medInria-public/wiki/Quick-Dev-Guide on medInria-public
