### ISSUE TITLE
Strange Rendering in 3D view after loading a surface mesh

### ISSUE THREAD

**Issue by nebatmusic** [medInria/medInria-public#504]
I am using macOS High Sierra (10.13.4) with Nvidia graphic card. 
Sometimes I have this strange rendering effect. 
<img width="190" alt="Screen Shot 2019-11-25 at 9 08 07 AM" src="https://user-images.githubusercontent.com/40757405/69523042-2713a800-0f63-11ea-93fe-86cf06e0f209.png">

Furthermore the buffer size's default value (QSurfaceFormat) in app/medInria/main.cpp are too low.

**Comment by Florent2305** [comment]
Ok what is the way to reproduce this bug or to have a little chance to reproduce it?
About buffer size, what buff are you talking about? Because in this class many buffer exist.
And what value do you recommend?

**Comment by nebatmusic** [comment]
Open a surface mesh on a mac with an nvidia graphic using qt 5.13 and let see what happens. 
I am talking about the following lines from main.cpp : 

     QSurfaceFormat fmt;
    fmt.setRenderableType(QSurfaceFormat::OpenGL);
    fmt.setVersion(3, 2);
    fmt.setProfile(QSurfaceFormat::CoreProfile);
    fmt.setSwapBehavior(QSurfaceFormat::DoubleBuffer);
    fmt.setRedBufferSize(1);
    fmt.setGreenBufferSize(1);
    fmt.setBlueBufferSize(1);
    fmt.setDepthBufferSize(1);
    fmt.setStencilBufferSize(0);
    fmt.setAlphaBufferSize(1);
    fmt.setStereo(false);
    fmt.setSamples(0);

I precise that the size are in bits. 

1 bit for a depth buffer size ? 

In  code provided as example,  you can often see values like : 

->setDepthBufferSize(24); // Profondeur du Double Buffer : 24

**Comment by mathildemerle** [comment]
There is a discussion about the depth number here: https://forum.qt.io/topic/33407/how-to-use-qsurfaceformat-instead-of-qglformat. In the link setStencilBufferSize can be changed also. However, are all these parameters need to be set?

**Comment by ocommowi** [comment]
We have put that configuration back at the time of changes of qt but more importantly vtk. This was a recommended one I found somewhere. But feel free to test other numbers. I would be careful though. Before validating anything we will need to check that it works on all systems.

These graphics bugs are the ugliest ones.

**Comment by nebatmusic** [comment]
**QVTKOpenGLSimpleWidget** had the same values for its default format but I don't know what for ? 

It seems that mac os will need specific code for Opengl and Qt (If you take for example QOpenGLWidget's doc there are several notes about mac os).
