### ISSUE TITLE
[Ubuntu16] do not compile

### ISSUE THREAD

**Issue by mathildemerle** [medInria/medInria-public#511]
medInria does not compile on Ubuntu 16. The gcc 5 compiler is not accepted, and C++17 also. 
In order to compile @mjuhoor needed to update the compiler, and change C++17 to C++11.

**Comment by Florent2305** [comment]
4 solutions are available:

- update the compiler to last version of gcc/g++ (My favorite)
- MUSIC fork of medInria set C++ version to Cxx14
- wait few months
- set C++ version to Cxx14 for medInria until april 2020 (The worth for me)


To update Gcc/G++:
`sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && `
`sudo apt-get update -y && `
`sudo apt-get install gcc-9 g++-9 -y && `
`sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ `
`/usr/bin/g++-9 && `
`sudo update-alternatives --config gcc`
