### ISSUE TITLE
[Efficiency] Opening of a data is slower than before

### ISSUE THREAD

**Issue by mathildemerle** [medInria/medInria-public#533]
In debug mode mostly, the opening of a data (not mesh in my tests) is slower than before, for instance on the MUSIC 2 state. The opening can be really really slower on some computers.

I circled the problem in: 
`medAbstractLayeredView::insertLayer` -> `medAbstractImageView::initiatiseInteractors` -> `medVtkViewItkDataImageInteractor::setInputData`.

In this last function, we used to have:

```c++
    if (!(SetViewInput<itk::Image<char,3> >("itkDataImageChar3", data, d->view->layer(data)) ||
          SetViewInput<itk::Image<unsigned char,3> >("itkDataImageUChar3", data, d->view->layer(data)) ||
          SetViewInput<itk::Image<short,3> >("itkDataImageShort3", data, d->view->layer(data)) ||
          SetViewInput<itk::Image<unsigned short,3> >("itkDataImageUShort3", data, d->view->layer(data)) ||
          SetViewInput<itk::Image<int,3> >("itkDataImageInt3", data, d->view->layer(data)) ||
          SetViewInput<itk::Image<unsigned,3> >("itkDataImageUInt3", data, d->view->layer(data)) ||
          SetViewInput<itk::Image<long,3> >("itkDataImageLong3", data, d->view->layer(data)) ||
          SetViewInput<itk::Image<unsigned long,3> >("itkDataImageULong3", data, d->view->layer(data)) ||
          SetViewInput<itk::Image<float,3> >("itkDataImageFloat3", data , d->view->layer(data)) ||
          SetViewInput<itk::Image<double,3> >("itkDataImageDouble3", data, d->view->layer(data)) ||
          SetViewInput<itk::Image<itk::RGBPixel<unsigned char>,3> >("itkDataImageRGB3", data, d->view->layer(data)) ||
          SetViewInput<itk::Image<itk::RGBAPixel<unsigned char>,3> >("itkDataImageRGBA3", data, d->view->layer(data)) ||
          SetViewInput<itk::Image<itk::Vector<unsigned char,3>,3> >("itkDataImageVectorUChar3", data, d->view->layer(data))))
    {
        qDebug() << "Unable to add data: " << data->identifier() << " to view " << this->identifier();
        return;
    }
```

And the new code is:

```c++
    if (!SetViewInput (data, d->view->layer(data)))
    {
        qDebug() << "Unable to add data: " << data->identifier() << " to view " << this->identifier();
        return;
    }
```
Which is way slower. It's calling `medVtkViewItkDataImageInteractor::SetViewInput` with `vtkItkConversionInterface` and these kind of new functions.

**Comment by mathildemerle** [comment]
@Florent2305 there is a problem with the scalar range (same as [[vtkusers] vtkResliceImageViewer::SetInputData() slow when executed after vtkDICOMImageReader::Update()](https://vtk.org/pipermail/vtkusers/2018-February/100918.html)) in `vtkImage2DDisplay::SetInput(vtkAlgorithmOutput *pi_poVtkAlgoPort)`. 

`m_sVtkImageInfo.SetScalarRange(poVtkImgTmp->GetScalarRange());` is really slow. According to the conversation above, it could be that the input is still empty at that point, something like that.

When you open a second time a same data, the time to open this data drops by the way.

**Comment by Florent2305** [comment]
Work in progress, good results for the moment.
The main optimizations are done in medVtkInria, thanks to a better use and comprehention of VTK.
