### ISSUE TITLE
[DICOM Import] Failure to import if path contains special characters

### ISSUE THREAD

**Issue by mjuhoor** [medInria/medInria-public#534]
medInria will fail to import DICOMs if the absolute path contains special characters.

1 - create directory named ` isdé_&"&'é""  `
2 - place a dicom inside
3 - import in medInria -> failure

This was previously solved with a brutal `QTextCodec::setCodecForCStrings(QTextCodec::codecForName("UTF-8"));`
but this static function is gone in Qt5

**Comment by nebatmusic** [comment]
Hello, 

I do not know if it will help : (bookmarked when porting to music3)

https://stackoverflow.com/questions/13968734/qtextcodecsetcodecforcstrings-is-gone-in-qt5 

best regards.

**Comment by Florent2305** [comment]
PR #535 focus the problem but not solve it on all operating systems
