### ISSUE TITLE
[PolygonROI] - Interpolation issues  

### ISSUE THREAD

**Issue by juliencastelneau** [medInria/medInria-public#544]
When I developed new feature in PolygonROI for APHP, we found an issue with interpolation.
Interpolations between slices are not uniformly smooth. Near master slices the interpolation is too brutal compared to the rest of the segment. 
It is an already known issue in medInria private repository ==> https://github.com/medInria/medInria-private/issues/159
It seems the problem occurs after decimation.

 See code below:
```
    QList<vtkPolyData *> listPolyData = generateIntermediateCurves(curveMax,curveMin,maxSlice-minSlice-1);
    double number = ceil(1.5 * (double)(curveMinNbNode));
    if (curveMaxNbNode > curveMinNbNode)
    {
        number = ceil(1.5 * (double)(curveMaxNbNode));
    }

    vtkImageView2D *view2d = static_cast<medVtkViewBackend*>(currentView->backend())->view2D;

    for (int i = minSlice+1;i<maxSlice;i++)
    {
        polygonRoi *polyRoi = new polygonRoi(view2d);
        vtkContourWidget *contour = polyRoi->getContour();
        contour->SetEnabled(true);

        // Points decimation // TODO put this in generateIntermediateCurves
        int nbPointsPoly = listPolyData[i-(minSlice+1)]->GetNumberOfPoints();
        int divPoly = (int)floor((double)nbPointsPoly/number);
        vtkPoints * points = listPolyData[i-(minSlice+1)]->GetPoints();
        vtkPoints * decimatedPoints = vtkPoints::New();

        for (int k = nbPointsPoly-1; k>=0; k--)
        {
            if (k%divPoly==0)
            {
                decimatedPoints->InsertNextPoint(points->GetPoint(k));
            }
        }
        listPolyData[i-(minSlice+1)]->SetPoints(decimatedPoints);

        contour->Initialize(listPolyData[i-(minSlice+1)]);

```
After discussion with @mathildemerle , this decimation is done to allow a better representation of intermediate contours on each slice.
But, the decimation is modifying the shape of contours...
TODO : Find a way to remove some points on contour while maintaining the contour.

**Comment by mathildemerle** [comment]
Concerning the decimation of points, it could be enhanced/added also in Extract ROI, in PolygonROI. The output of Extract ROI is really long to compile and has no decimation for now.

**Comment by mathildemerle** [comment]
By the way, @juliencastelneau does your PR solve this issue?

**Comment by juliencastelneau** [comment]
Yes. I think we could find a better solution. But for now, the results seems good for practician.
