### ISSUE TITLE
Layer 0 deletion crashing bug

### ISSUE THREAD

**Issue by ocommowi** [medInria/medInria-public#554]
Here is a nasty one we thought was solved. Do this to get the crash in medinria 3.1.0:

- load T13D.nii.gz from medinria data
- load the fibers study_tumor_fibers_T1.xml from medinria-data
- while still in axial mode (you shouldn't have changed), remove the T1 layer
- switch to 3D mode and the app crashes

**Comment by mathildemerle** [comment]
This bug can be found on master and 3.1. Before switching to 3d, the incoming crash can be seen: if you remove the T1 layer, the view is not updated and you can still see the T1 but not the fiber

**Comment by mathildemerle** [comment]
i updated my previous message

**Comment by mathildemerle** [comment]
Does this PR https://github.com/medInria/medInria-public/pull/562 fix this issue?
