### ISSUE TITLE
Compilation error missing #endif in DCMTK/config/include/dcmtk/config/arith.h

### ISSUE THREAD

**Issue by riep** [medInria/medInria-public#563]
Hi everyone, 
There is a missing #endif statement at the end of  medInria_ExtProjs/build/DCMTK/config/include/dcmtk/config/arith.h file. This causes a compilation error/crash of DCMTK lib.
I don't know exactly where this file is comming from, not from https://github.com/DCMTK/dcmtk apparently ...

**Comment by ocommowi** [comment]
Hi !

Thanks for reporting this. Could you tell us on which os and cmake version you are ? This file is actually an automatically generated one and on my os (macos) it is generated fine with the #endif at the end.

It might be a problem linked to a specific os / cmake version problem but in any case adding the endif is a temporary solution for you as the next time cmake will regenerate the file, the bug will re-appear. 

If you keep having that trouble, we could also think of moving to a more recent version of dcmtk (we have this in our pipeline but not a priority yet)

**Comment by Florent2305** [comment]
Hi !

Thanks for reporting this.
I'm on Windows and I use VS2017 and CMake 3.14 without any problem.
To my knowledge Mathilde don't have any problem on Ubuntu.

If you have enough time to rebuild from scratch, this may be a way to test.

Best regards
Florent

**Comment by riep** [comment]
I am using WSL (Windows Subsystem for Linux) and Ubuntu 18.04.4 LTS and cmake version 3.10.2

**Comment by Florent2305** [comment]
Indeed, we never test this configuration.

**Comment by riep** [comment]
anyway if this problem occures only on WSL this is probably not important. Though, I don't know what could change from a standard ubuntu ...

**Comment by Florent2305** [comment]
Can I close this issues ?
