### ISSUE TITLE
[Tests] 3.1.1 and master, Browser -> View and Index useless

### ISSUE THREAD

**Issue by mathildemerle** [medInria/medInria-public#580]
On the 3.1.1 branch at least, in the Browser workspace -> Filesystem:
 * Double click on a mha (or vtk) for instance -> nothing happen
 * Click on View in the same data -> nothing happen
 * Click on Index in the same data -> a progress bar is displayed, succeed -> i don't know what have been done, nothing in the DB.

**Comment by mathildemerle** [comment]
This is the same behavior on master (4.0)

**Comment by Florent2305** [comment]
It's actually too complicated with too many functions.
Functions are often so close it doesn't have any interest to keep all buttons.
I suggest to keep only :
-  View
- Temporary import
- Import

Bookmark will still accessible via contextual menu
