### ISSUE TITLE
2 Volumes and Volume Rendering

### ISSUE THREAD

**Issue by nbaraka** [medInria/medInria-public#603]
**2 Volumes in a boat : the second one jump (closed) ...**

Here the steps : 
Open 2 volumes. 
switch to 3D and VR. 
close the second one (layer)
switch to 2d 
go back to 3d 
--- > crash 

No pb if it is the first one that is closed.

**Comment by nbaraka** [comment]
I working on it.

**Comment by mathildemerle** [comment]
This crash can also be found on 3.1.1 branch

**Comment by Florent2305** [comment]
I reproduce this issues

**Comment by nbaraka** [comment]
I have worked on it yesterday. 
The workflow is simpler : open two volumic data. close one of them. switch to 3d and enable volume rendering  --> crash.

**Comment by nbaraka** [comment]
First idea : vtkImageView2D.cxx and code below // Make contiguous. This is not done for vtkImageView3D.cxx

**Comment by Florent2305** [comment]
> First idea : vtkImageView2D.cxx and code below // Make contiguous. This is not done for vtkImageView3D.cxx

code below ?

**Comment by nbaraka** [comment]
Second idea : Interactors are created only one time when first  data is loaded (attached in a way to the view) but deleted  as soon a data is removed : **void medAbstractLayeredView::removeInteractors(medAbstractData *data)**

**Comment by nbaraka** [comment]
> > First idea : vtkImageView2D.cxx and code below // Make contiguous. This is not done for vtkImageView3D.cxx
> 
> code below ?
code the below the comment make contiguous : 
        for ( size_t i(0); i<this->LayerInfoVec.size(); ++i )
        {
            if( this->LayerInfoVec[i].Renderer )
                this->LayerInfoVec[i].Renderer->SetLayer(static_cast<int>(i));
            this->SetCurrentLayer(static_cast<int>(i));
        }

**Comment by Florent2305** [comment]
thanks

**Comment by nbaraka** [comment]
You're welcome. If you comment these lines. No more crash , the 2d views are fine only the Volume rendering is not updated correctly (there is still the actor for the data that have been removed) but MSR is ok.

**Comment by nbaraka** [comment]
It does not take into the layer that has been closed. It any case it close the one that is currently selected. 
Seems strange.

**Comment by nbaraka** [comment]
debug mode : watch the layer number.

**Comment by nbaraka** [comment]
The pb is in the difference between the following 2 functions in how they compute the layer number : 
void medAbstractWorkspaceLegacy::removeLayer()

void medVtkViewItkDataImageInteractor::removeData()

**Comment by Florent2305** [comment]
> It does not take into the layer that has been closed. It any case it close the one that is currently selected.
> Seems strange.
This type of issues is already come across during the past and it's due to a regression but it was very easy to solve.

**Comment by nbaraka** [comment]
this  this->removeInteractors(data) should be called after
   if(d->layersDataList.count() != 0  && layer == d->layersDataList.count())
    {
        this->setCurrentLayer(layer -1);
    }
    else if(d->layersDataList.count() != 0)
    {
        this->setCurrentLayer(layer);
    }

in medAbstractLayeredView.

**Comment by nbaraka** [comment]
Final sol . forget the previous one. 
At least call **this->setCurrentLayer(layer);** in  void **medAbstractLayeredView::removeLayer**(unsigned int layer) before  this->removeData(this->layerData(layer));  or in **medAbstractWorkspaceLegacy::removeLayer().**

**Comment by mathildemerle** [comment]
Great, can you create a PR with this final solution? On 3.1.1 and master if it's possible, since it's a critical bug :)

**Comment by Florent2305** [comment]
@nbaraka I send you an email
