### ISSUE TITLE
Build error in master 

### ISSUE THREAD

**Issue by nbaraka** [medInria/medInria-public#627]
could not build in master (6fb1a4ca4c13ea819629559993ce096039ceb807) ( on ubuntu 18. 
I got the following error : 
/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydataops.h:122:62: error: source file is not valid UTF-8
due to an assert in this file : assert in line 121

**Comment by nbaraka** [comment]
ok after reboot.

**Comment by Florent2305** [comment]
Strange
