### ISSUE TITLE
Freeze when opening 2nd nrrd file

### ISSUE THREAD

**Issue by nbaraka** [medInria/medInria-public#630]
In an empty visualization, I use the tool to open a first nrrd file. Seems Ok. But when I open the second one, it freeze and the HMI is strange. 
![freezing](https://user-images.githubusercontent.com/1786923/80082872-3a985e80-8555-11ea-98ad-527bc4953a82.png)

**Comment by mathildemerle** [comment]
It seems to be the same bug as https://github.com/medInria/medInria-public/issues/593

**Comment by nbaraka** [comment]
By commenting this->blockSignals(true) and this->blockSignals(false) in QImage medVtkView::buildThumbnail(const QSize &size) I do not the pb anymore. 

It may block signal used in medDataSourceManager or related classes.

**Comment by mathildemerle** [comment]
It's also linked to https://github.com/medInria/medInria-public/issues/608

Oh nice, i saw that addLayer was a part of the problem in medAbstractData::generateThumbnailInGuiThread but i did not see the blockSignals :)
