### ISSUE TITLE
3D mode crash for Image with vector data or tensor when data is 2D:   "itkDataImageVectorFloat3

### ISSUE THREAD

**Issue by nbaraka** [medInria/medInria-public#640]
After the import of an image with vector data (3), there is a crash during the change of orientation in the 3d mode. 
(the image is result of computing  gradient of a dicom and saving it in mha file) 

@Florent2305 this bug impact also tensors glyph

**Comment by mathildemerle** [comment]
Hi @nbaraka , do you have a data creating the crash we could test?

**Comment by mathildemerle** [comment]
I have the crash on Ubuntu, on master branch in `vtkInteractorStyleTrackballCamera2::Rotate()` line 102 `rwi->Render();`

Thx for the test data.

**Comment by nbaraka** [comment]
You're welcome. 
I got the same error. I was doing some test to replace vtkGlyph with vtkGlyphMapper which according to https://blog.kitware.com/wp-content/uploads/2016/01/kitware_quarterly1011.pdf has better perf.

**Comment by mathildemerle** [comment]
Does this PR https://github.com/medInria/medInria-public/pull/647 solve this issue @nbaraka ?
