### ISSUE TITLE
2 volumes in VR  & close 

### ISSUE THREAD

**Issue by nbaraka** [medInria/medInria-public#656]
When 2 volumes are opened in the VR mode and one of them is closed then the VR is like freezing. I have to go back to 2D display to solve the pb.

**Comment by mathildemerle** [comment]
I do not success to recreate this bug, do you still have it on the master or 3.1.x branch?

**Comment by nbaraka** [comment]
solved by #661

**Comment by mathildemerle** [comment]
Great, i close this issue
