### ISSUE TITLE
RESLICER crash with some parameters 

### ISSUE THREAD

**Issue by nbaraka** [medInria/medInria-public#669]
Changing the parameters spacing create a crash. 
But i got an idea on this.

**Comment by nbaraka** [comment]
@mathildemerle : I think that in **applyResamplingPix** ,  resamplePr->setParameter(outputSpacing[0], 0) should be  resamplePr->setParameter(outputSpacing[0], 3) 
and ... 
Do you agree ?

**Comment by mathildemerle** [comment]
```c++
    resamplePr->setParameter(outputSpacing[0], 3);
    resamplePr->setParameter(outputSpacing[1], 4);
    resamplePr->setParameter(outputSpacing[2], 5);
```
This? It could be indeed, as far as i see, but i did not test :)

**Comment by nbaraka** [comment]
ok thanks I will give it a try.
