### ISSUE TITLE
[3D] transparency and hide/show problems

### ISSUE THREAD

**Issue by mathildemerle** [medInria/medInria-public#670]
There are some problems in the 3D view, mainly:
 
* [2 Volume VR & LUT](https://github.com/medInria/medInria-public/issues/657), solved by @nbaraka PR 
 * [once min/max intensities in 3D, it's kept](https://github.com/medInria/medInria-public/issues/581) 

There are also some opacity, and widgets problems:
 * Open a data, switch to 3D: the opacity of the layer does not work (the slider)
 * Open 2 data, switch to 3D: the opacity slider and the small thumbnail of the layer to hide/show the layer do not work

**Comment by Florent2305** [comment]
Quick informative response:

> Open a data, switch to 3D: the opacity of the layer does not work (the slider)

This has never work/effect on images in 3D handle by itkDataImage Plugin on classic medInria flavor.
2 options:
- Does an effects, this is a new specific development
- Opacity slider become grey on 3D
<br>

> Open 2 data, switch to 3D: the opacity slider and the small thumbnail of the layer to hide/show the layer do not work 

3D juste display the 1st image layer (not include tensor, vector, fiber and mesh)

**Comment by Florent2305** [comment]
The two main problems are solved, and other "issues" (normal behavior up to now) are note major bugs.

I propose a small partial workaround into my branch :
https://github.com/Florent2305/medInria-public/tree/opacityMSR_Layer0
So, after theses corrections and enhancement I decide to convert this bug issue to an discussion issue.

We can re-convert it in the future if it's needed

**Comment by mathildemerle** [comment]
solved
