### ISSUE TITLE
Visualization Text Information Displayed & multi layers 

### ISSUE THREAD

**Issue by nbaraka** [medInria/medInria-public#673]
Text Information Displayed in top left visualization window is not updated when another layer is selected. 
Test done with nrrd images

**Comment by mathildemerle** [comment]
Weird, it's working on my side (i tested on the master branch)

**Comment by mathildemerle** [comment]
Oh, when you add a layer to an other, there is a resampling, changing the spacing/size. Is it the problem you saw? Because the pixel value, and windowing (WW/WL) are updated when you select an other layer

**Comment by nbaraka** [comment]
Yes it was the spacing. an original image and the result of reslice change of spacing. 
Strange : If I have a high resol image loaded as the 1st layer then the second on (low res) will be like "resliced" to have the same reso without launching reslice.
