### ISSUE TITLE
CTRL + LEFT CLICK & SCROLL & CROP 

### ISSUE THREAD

**Issue by nbaraka** [medInria/medInria-public#675]
Inside the view, if you click ctrlt + lef you add/remove the layer from the tab. 

That seems strange for me.  This is implemented in **bool medAbstractView::eventFilter(QObject * obj, QEvent * event)**

**IS IT NEEDED !! WHAT FOR ?** 

For example it creates a crash in CROP from REFORMAT. IF it is done insinde the crop's bouding box. 

Because you can also ctrl + scroll to chance the slice. 
**But in a mac scroll and left click is almost the same**

**Comment by mathildemerle** [comment]
The control-click to select or unselect a view is normal. If you have multiple views, you can select the views you want, and for instance change the Link view and layer properties in the "View settings" or "Layer settings" toolbox. The views could be linked. 

But, the toolboxes need to be updated when the current view is unselected, and should not bug. If there is a bug in Cropping, this should be indeed solved.

**Comment by mathildemerle** [comment]
this problem can't be found anymore
