### ISSUE TITLE
DiffeomorphicDemons Freeze at the end

### ISSUE THREAD

**Issue by Florent2305** [medInria/medInria-public#695]
some logs:

> DEBUG - Thu May 14 10:24:01 2020 - ""DiffeomorphicDemons\n  Max number of iterations   : [ 15, 10, 5 ]\n  Update rule   : DIFFEOMORPHIC\n  Gradient type   : SYMMETRIZED\n  Maximum step length   : 2 (voxel unit)\n  Update field standard deviation   : 0 (voxel unit)\n  Displacement field standard deviation   : 1.5 (voxel unit)\n  Use histogram matching   : false\n"" 
> DEBUG - Thu May 14 10:24:08 2020 - "Elasped time:  52.894" 
> DEBUG - Thu May 14 10:24:08 2020 - "medDatabaseNonPersistentImporter created with uuid: "{17ef33a1-04ae-4a4c-a089-72b95244e319}"" 
> INFO  - Thu May 14 10:24:08 2020 - "generating data for image factory" 
> DEBUG - Thu May 14 10:24:08 2020 - medAbstractImageData has no such property: "SeriesDescription"

data to reproduce bug:
https://filesender.renater.fr/?s=download&token=b6bcf1cb-0b5e-4be7-9395-2f6c48127b70

**Comment by Florent2305** [comment]
At the end of diffeomorphic demons processus the call stack as follow:

|      FUNCTION                                                                               |   SOURCE FILE                                                                              | MODULE   |      DLL                       |
| ------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------ | -------- | ------------------------------ |
|  itk::ImageRegistrationFactory<itk::Image<float,3> >::GenerateData()                        | medinria_extprojs/src/rpi/registrationaddon/itkimageregistrationfactory.txx(45)            | RPI      | medRegistration.dll            |
|  itk::ProcessObject::UpdateOutputData(itk::DataObject * __formal)                           | medinria_extprojs/src/itk/modules/core/common/src/itkprocessobject.cxx(1778)               | ITK      | ITKCommon-5.0.dll              |
|  itk::DataObject::UpdateOutputData()                                                        | medinria_extprojs/src/itk/modules/core/common/src/itkdataobject.cxx(411)                   | ITK      | ITKCommon-5.0.dll              |
|  itk::ImageBase<3>::UpdateOutputData()                                                      | medinria_extprojs/src/itk/modules/core/common/include/itkimagebase.hxx(293)                | ITK      | medRegistration.dll            |
|  itk::DataObject::Update()                                                                  | medinria_extprojs/src/itk/modules/core/common/src/itkdataobject.cxx(334)                   | ITK      | ITKCommon-5.0.dll              |
|  itk::ProcessObject::Update()                                                               | medinria_extprojs/src/itk/modules/core/common/src/itkprocessobject.cxx(1347)               | ITK      | ITKCommon-5.0.dll              |
|  undoRedoRegistration::generateOutput(bool algorithm, dtkAbstractProcess * process)         | medinria/src/plugins/legacy/undoredoregistration/undoredoregistration.cpp(86)              | MEDINRIA | undoRedoRegistrationPlugin.dll |
|  undoRedoRegistrationToolBox::onRegistrationSuccess()                                       | medinria/src/plugins/legacy/undoredoregistration/undoredoregistrationtoolbox.cpp(198)      | MEDINRIA | undoRedoRegistrationPlugin.dll |
|  undoRedoRegistrationToolBox::qt_static_metacall(QObject* , QMetaObject::Call, int, void**) | moc_undoredoregistrationtoolbox.cpp(95)                                                    | MOC_MED  | undoRedoRegistrationPlugin.dll |
|  QMetaObject::activate()                                                                    |                                                                                            | Qt       | Qt5Cored.dll                   |
|  QMetaObject::activate()                                                                    |                                                                                            | Qt       | Qt5Cored.dll                   |
|  medToolBox::success()                                                                      | moc_medtoolbox.cpp(286)                                                                    | MOC_MED  | medCoreLegacy.dll              |
|  medToolBox::qt_static_metacall(QObject*, QMetaObject::Call, int _id, void **)              | moc_medtoolbox.cpp(144)                                                                    | MOC_MED  | medCoreLegacy.dll              |
|  QMetaObject::activate()                                                                    |                                                                                            | Qt       | Qt5Cored.dll                   |
|  QMetaObject::activate()                                                                    |                                                                                            | Qt       | Qt5Cored.dll                   |
|  medToolBox::success()                                                                      | moc_medtoolbox.cpp(286)                                                                    | MOC_MED  | medCoreLegacy.dll              |

The ` std::cout<<"generating data for image factory"<<std::endl; `  of  itkimageregistrationfactory.txx(45) of RPI create a deadlock throw **dtkLogEnginePrivate**::write(void)

**Comment by mathildemerle** [comment]
Same problem in Manual Registration : https://github.com/medInria/medInria-public/issues/585 i close the first one

**Comment by mathildemerle** [comment]
LCC-LogDemons freezes also at the end

**Comment by mathildemerle** [comment]
@Florent2305 i tested your branch with the "music" logger, and it solves this issue. However, your branch does not compile unless you use also https://github.com/medInria/medInria-public/pull/702 or https://github.com/medInria/medInria-public/pull/700 which could be merged before yours. 
So: great, a critical issue solved :)
