### ISSUE TITLE
ReSLICE : view are too small 

### ISSUE THREAD

**Issue by nbaraka** [medInria/medInria-public#727]
ReSLICE has too small view. 

OS : ubuntu 19
Branch status : medInria3.1.x, commit : e38b1e8c787527e690f1ac93f283c25e78b8fb5b

![reslice](https://user-images.githubusercontent.com/1786923/83762239-9d623700-a677-11ea-933f-9148a0e6d5d5.png)

**Comment by mathildemerle** [comment]
Weird, i do not have this problem, on Ubuntu 18.04:
![ResliceOk](https://user-images.githubusercontent.com/3910352/83764006-ac49e900-a679-11ea-9632-982281abf828.png)

**Comment by Florent2305** [comment]
I have the bug on my side
![reslice](https://user-images.githubusercontent.com/7893917/83767369-dd2c1d00-a67d-11ea-9109-402b6629a08a.PNG)

**Comment by mathildemerle** [comment]
In fact it was a problem i solved few month ago, but i put back the problem 6 days ago, my bad :D. We're on it with @Florent2305
