### ISSUE TITLE
To compile with qt5.15 

### ISSUE THREAD

**Issue by nebatmusic** [medInria/medInria-public#756]
Hello, 

The qt5.15 is the current default release you get with brew. 

But it has compilation issue with vtk. 

The sol. could be to patch VTK. (one header to add to 2 files). (tested it works)

**vtkQtLabelRenderStrategy** 
**vtkQtStringToImage**

**Comment by Florent2305** [comment]
The other solution is to use official Qt installer.
It's tested by @juliencastelneau

**Comment by nebatmusic** [comment]
Julien has choiced Qt installer because he got the compile issues and can not choose an older qt release via brew so he took the qt installer. 

What I propose is to solve the compile issues to be able to use the last  lts qt release.  the stepping stone towards qt 6. https://www.qt.io/blog/qt-5.15-released. 

the way dep. are installed is not changed : via brew. (the apt for mac os). 

I do not wait for VTK to do the job and so let them choice which qt release I can use. 

Patch are good temp sol (other softwares has solved the compile issues with the same sol)

**Comment by juliencastelneau** [comment]
Agree with Nordine.
Maybe we could fork instead of patch VTK ?

**Comment by nebatmusic** [comment]
We used to patch VTK. and since it is really a minor change it is not a good reason to  "fork" @juliencastelneau (maybe you have other reasons)

The pb is solved on master and maybe vtk 9.0 (https://gitlab.kitware.com/vtk/vtk/-/issues/17927, https://gitlab.kitware.com/vtk/vtk/-/issues/17921). 

We are know using v8.1.2.

**Comment by ocommowi** [comment]
We have a way to apply our custom patches to external repos we use. But this can be a bit painful sometimes. And VTK 9 probably has the patch already included so I would rather go for moving to VTK 9 once we are sure there is no other problem coming with it in visualization

**Comment by nebatmusic** [comment]
This patch is minor (to include one qt header into 2 files) and it will allow users to work with the last qt.  

[VTK.patch.txt](https://github.com/medInria/medInria-public/files/4952446/VTK.patch.txt)
