### ISSUE TITLE
[Database] Saving to permanent database fails to find existing patient or study

### ISSUE THREAD

**Issue by mjuhoor** [medInria/medInria-public#757]
Steps:
- Assume the database has already the patient named "John Doe", with an existing study "Empty study"
- Temporary import any 2 meshes : these are put in the temporary  _John Doe_ patient, _Empty study_ study.
- Save the first mesh: it is not saved in the existing "Empty Study". Instead it creates a duplicate one.
- Save the second mesh: again, a third "Empty Study" is created.

Additional info:
Sometimes even the patient is duplicated.

Fails for images and other types too, not just meshes
Don't know if it's a real database bug, or just a 'visual' bug related to the QTreeWidget items.
Tested with current medInria 3.1.1 release, and MUSIC current dev. branch.

**Comment by mjuhoor** [comment]
I think I will solve this in our medInria fork and then I can send or you can retrieve the fix. To me this bug is really problematic for users and we cannot wait for the 4.0 release.

**Comment by mathildemerle** [comment]
(as said on mattermost, we'll do a 3.2 branch on the master, so no problem with a debug on this master)

**Comment by mathildemerle** [comment]
@mjuhoor do you have news about this bug? I found it too, mostly with Study names

**Comment by mjuhoor** [comment]
I have not experienced this bug recently. Was it with images for you ?

**Comment by mathildemerle** [comment]
I temporary imported dicoms, then saved them, and each one of them have been saved in his own "EmptyStudy" ^^

**Comment by mathildemerle** [comment]
The bug has been found also by a user, i switch the issue to critical since it's really complicated to use the software with this problem.

**Comment by mjuhoor** [comment]
> Dear all, 
as suggested I post here a bug report on patient records management. It looks like the one posted by Medhi but not exactly (https://github.com/medInria/medInria-public/issues/757)
I'm trying to have stored in the database a patient file named Brebis19112020 with all the vtk meshes that have been previously segmented. When I drag to Music the folder that contains my vtk meshes; Music creates a John Doe patient that I rename ‘Brebis19112020’ and a empty study. 
Music crashes both when I ask it to save by right-clicking on John Doe ‘Save’ or when I use the save command prompt at the exit of the program with the checkboxes to select for each mesh. When I reopen the program, all the meshes do not appear and are not correctly classified in a single 'emptyStudy'. 
Attached is a folder with meshes for testing.
Thank you for your help. 
Rémi
