### ISSUE TITLE
[Diffeomorphic] data + mask crash

### ISSUE THREAD

**Issue by mathildemerle** [medInria/medInria-public#794]
[Test of the Ubuntu20 Jenkins binary on a Ubuntu20 computer]

 * Open a data and its mask
 * Run
 * Crash:

```
WARN  - mar. nov. 10 15:39:13 2020 - "QMutex: destroying locked mutex" 
DEBUG - mar. nov. 10 15:39:13 2020 - "METHOD PARAMETERS" 
DEBUG - mar. nov. 10 15:39:13 2020 - "\"DiffeomorphicDemons\\n  Max number of iterations: [ 15, 10, 5 ]\\n  Update rule: DIFFEOMORPHIC\\n  Gradient type: SYMMETRIZED\\n  Maximum step length: 2 (voxel unit)\\n  Update field standard deviation: 0 (voxel unit)\\n  Displacement field standard deviation: 1.5 (voxel unit)\\n  Use histogram matching: false\\n\"
[...]
Program terminated with signal SIGKILL, Killed.
```

Same crash on medInria and MUSICardio.

**Comment by mathildemerle** [comment]
Update: this crash happens in Diffeomorphic toolbox and LCC Log Demons, but the process succeeds with Optimus. 
They are [RPI](https://github.com/Inria-Asclepios/RPI) processes, and it crashs in the registration `StartRegistration()` methods. The `try catch` on our sides do not catch the error. It happens with a CT i have, and its polygonROI segmentation binary mask in 0 and 1. Do i move this issue on the RPI repo?

**Comment by ocommowi** [comment]
hmm I would try to use the non medinria versions of the tools. I have the feeling the problem may come from the algorithm itself. Was it working before or is it the first time you try such a registration (mask vs image) ?

**Comment by mathildemerle** [comment]
We already had several crashs of the application from some Registration toolboxes, and indeed mostly because we are using it wrongly i think (like my CT scan + its binary mask). 

It seems that the algorithms do not send exceptions in case of problem, and crash (and then the application crashes). We are trying to catch exceptions in medInria, but it is then useless. 

In order to avoid the crash, we can forbid the user in medInria to use wrongly the toolbox, or RPI could send exceptions in case of a inner-crash, or we could catch exceptions if there is a possibility

**Comment by mathildemerle** [comment]
Linked to https://github.com/medInria/medInria-public/issues/965
