### ISSUE TITLE
[Binary Operation] XOR, AND, OR do not succeed

### ISSUE THREAD

**Issue by mathildemerle** [medInria/medInria-public#797]
[Test of the Ubuntu20 Jenkins binary on a Ubuntu20 computer]

 * Open 2 masks, same sizes and spacing sizes
 * Run -> process fails

Logs:
```
DEBUG - jeu. nov. 12 11:12:52 2020 - "itkDataImageReaderBase :: found unknown key: \"ITK_InputFilterName\"" 
[New Thread 0x7fff4c92d700 (LWP 36174)]
ExceptionObject caught in itkXorOperator

itk::ExceptionObject (0x7fff400051c0)
Location: "unknown" 
File: /builds/workspace/music-ubuntu20-free/ExtProjs/ITK/Modules/Core/Common/include/itkImageToImageFilter.hxx
Line: 230
Description: itk::ERROR: XorImageFilter(0x7fff40001c00): Inputs do not occupy the same physical space! 
InputImage Spacing: [4.5507800e-01, 4.5507800e-01, 9.1015231e-01], InputImage_1 Spacing: [4.5507800e-01, 4.5507800e-01, 9.1015400e-01]
	Tolerance: 4.5507800e-07

DEBUG - jeu. nov. 12 11:12:53 2020 - "Binary Operation: This action failed (undefined error)"
```

Same error on medInria and MUSICardio.

**Comment by mjuhoor** [comment]
I have trouble reproducing this bug. It seems it's highly input dependant.

**Comment by mathildemerle** [comment]
I retry with 2 masks at 0/1 values, but ive got the same problem

**Comment by paulineMig** [comment]
Can you give us the masks please

**Comment by paulineMig** [comment]
You're input mesh does not have the same z spacing that is why it does not work if you resample one of the mask it works as it should

**Comment by mathildemerle** [comment]
?why do i have a different z spacing? Oki, so the toolbox did not crash, it's a good point for it. Thanks for the tests, i'm closing the issue :)
