### ISSUE TITLE
[DICOM] - Import 2 series while there is only one 

### ISSUE THREAD

**Issue by juliencastelneau** [medInria/medInria-public#806]
- Go to Browser
- Choose a dicom directory (with 16 dicom file for instance)
- Import (or temporary import)
- open Visualisation workspace
==> In Patient/Study, you can see 2 series with 8 slices each.

It is not the case with all data.
I experienced it with a set of data. Try to import in Slicer or read with a python script. There is only one serie...
[100.000000-DCE Subtraction-32256.zip](https://github.com/medInria/medInria-public/files/5597859/100.000000-DCE.Subtraction-32256.zip)

**Comment by mjuhoor** [comment]
3D Slicer, ImageJ and itkSnap see only 1 series.

**Comment by mjuhoor** [comment]
Solved in #807
