### ISSUE TITLE
Anima plugins are not in packaged medinria for windows

### ISSUE THREAD

**Issue by ocommowi** [medInria/medInria-public#819]
As it says, there is a problem in the packaging of medinria for windows (at least 3.1.1). The anima plugins are not there in the package downloaded from the website

**Comment by ocommowi** [comment]
This has been solved I believe. It was a jenkins configuration problem

**Comment by Florent2305** [comment]
Yes it solved into 3.2.0
It right,  It was a jenkins configuration problem.
